# MIT License
#
# Copyright (c) 2024-2026 Inverse Materials Design Group
#
# Author: Ihor Radchenko <yantar92@posteo.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""VASP adapter for gorun."""

from __future__ import annotations

import os
import re
from pathlib import Path

from termcolor import colored

from IMDgroup.gorun.adapters.base import SoftwareAdapter
from IMDgroup.gorun.cleanVASP import (
    check_incar,
    clean_vasp_inputs,
    clear_useless_vasp_files,
    clear_vasp_outputs,
    contcar_to_poscar,
    directory_contains_vasp_outputp,
    directory_converged_p,
    generate_potcar,
    mdp,
    nebp,
    put_vdw_kernel,
)
from IMDgroup.gorun.core.files import maybe_regenerate
from IMDgroup.gorun.slurm import clear_slurm_logs


# ---------------------------------------------------------------------------
# INCAR.py wrapping snippets
# ---------------------------------------------------------------------------

_PYTHON_HEADER = """
from pathlib import Path
from ase.calculators.vasp import Vasp
from ase.io import read as ase_read
from IMDgroup.gorun.cleanVASP import generate_potcar
from IMDgroup.pymatgen.io.vasp.vaspdir import IMDGVaspDir

# Replace ASE's POTCAR generation with your function
def custom_write_potcar(self, suffix="", directory='.'):
    '''Use our generate_potcar function instead of ASE's'''
    generate_potcar(path=directory, keep_existing=False)

calc=Vasp(directory='.', txt='-')

# Replace the method on this instance
calc.write_potcar = custom_write_potcar.__get__(calc, type(calc))

# Already copied from INCAR.X if necessary
calc.read_incar('INCAR')
# auto-generated by gorun if necessary
calc.read_potcar('POTCAR')
calc.read_kpoints('KPOINTS')

# POSCAR can be a copy of CONTCAR as needed
atoms = ase_read('POSCAR', format="vasp")
atoms.calc = calc

# Setup IMDGVaspDir
vaspdir = IMDGVaspDir('.')

# Mark UNCONVERGED
Path("UNCONVERGED").touch()
"""

_PYTHON_FINALIZER = """
Path("UNCONVERGED").unlink()
"""


# ---------------------------------------------------------------------------
# VaspAdapter
# ---------------------------------------------------------------------------


class VaspAdapter:
    """``gorun vasp`` backend."""

    name = "vasp"
    log_file = "vasp.out"

    def __init__(
        self, *,
        vasp_variant: str = "ncl",
        no_incar_py: bool = False,
        no_vasp_config: bool = False,
        no_clean: bool = False,
        incar_mods: dict[str, str] | None = None,
    ) -> None:
        self.vasp_variant = vasp_variant
        self.no_incar_py = no_incar_py
        self.no_vasp_config = no_vasp_config
        self.no_clean = no_clean
        self.incar_mods = incar_mods

    # ------------------------------------------------------------------
    # Environment
    # ------------------------------------------------------------------

    def validate_environment(self) -> None:
        """Require ``VASP_PATH`` and ``VASP_PP_PATH``."""
        missing = []
        for var in ("VASP_PATH", "VASP_PP_PATH"):
            if var not in os.environ:
                missing.append(var)
        if missing:
            raise OSError(
                f"Required environment variables not set: {', '.join(missing)}"
            )

    # ------------------------------------------------------------------
    # Directory inspection
    # ------------------------------------------------------------------

    def is_valid_input(self, path: Path) -> bool:
        return (path / "INCAR").is_file()

    def is_converged(self, path: Path) -> bool:
        """True when converged and no INCAR chains remain.

        INCAR chains mean the job is not truly finished -- there are
        more INCAR variants to try.
        """
        if not directory_converged_p(str(path)):
            return False
        # MD runs never chain.
        if mdp(str(path)):
            return True
        # Converged, but more INCARs to process?  Then not done.
        if _has_incar_chain(path):
            return False
        return True

    def has_previous_output(self, path: Path) -> bool:
        """True when VASP output or INCAR.py exists.

        Matches the original backup condition in gorun.py.
        """
        if not self.no_incar_py and (path / "INCAR.py").is_file():
            return True
        return directory_contains_vasp_outputp(str(path))

    # ------------------------------------------------------------------
    # Preparation
    # ------------------------------------------------------------------

    def prepare_inputs(
        self,
        path: Path, *,
        keep: set[str] | None = None,
        force: bool = False,
        **kwargs,
    ) -> None:
        if keep is None:
            keep = set()

        _clear_useless_files(path)

        # -- INCAR chain rotation --
        if not mdp(str(path)) and not force:
            _rotate_incar_chain(path)

        # -- INCAR modification --
        if self.incar_mods:
            _modify_incar(path, self.incar_mods)

        # -- Main preparation (single directory) --
        self._prepare_single(path, keep)

        # -- NEB subdirectories --
        if nebp(str(path)):
            for entry in sorted(path.iterdir()):
                if entry.is_dir() and re.match(r"[0-9]+", entry.name):
                    self._prepare_single(entry, keep)
            if not self.no_clean:
                for entry in sorted(path.iterdir()):
                    if entry.is_dir() and re.match(r"[0-9]+", entry.name):
                        clear_slurm_logs(str(entry))

    def _prepare_single(self, path: Path, keep: set[str]) -> None:
        """Prepare one VASP directory (main or NEB sub)."""
        check_incar(str(path))

        # CONTCAR → POSCAR
        poscar = path / "POSCAR"
        if "POSCAR" in keep and poscar.is_file():
            print(f"Keeping existing POSCAR")
        elif "POSCAR" in keep:
            print(
                "--keep POSCAR requested but POSCAR does not exist.  "
                "Copying CONTCAR if available."
            )
            contcar_to_poscar(str(path))
        else:
            contcar_to_poscar(str(path))

        # Clean input files
        clean_vasp_inputs(str(path))

        # POTCAR
        maybe_regenerate(
            path, "POTCAR", keep,
            regenerate=lambda: _regenerate_potcar(str(path)),
        )

        # vdW kernel
        put_vdw_kernel(str(path))

        # Clear old outputs
        clear_vasp_outputs(str(path))

    # ------------------------------------------------------------------
    # Script generation
    # ------------------------------------------------------------------

    def setup_commands(self, server_config: dict) -> str:
        """Extract VASP module setup from config.

        Looks for ``server_config["vasp"]["setup"]`` first,
        then falls back to the legacy ``server_config["VASP-setup"]`` key.
        """
        if self.no_vasp_config:
            return ""

        vasp_cfg = server_config.get(self.name, {})
        if vasp_cfg:
            return vasp_cfg.get("setup", "")
        # Legacy flat config
        return server_config.get("VASP-setup", "")

    def generate_run_commands(self, path: Path, server_config: dict) -> str:
        if not self.no_incar_py and (path / "INCAR.py").is_file():
            return self._incar_py_script(path)
        return self._direct_vasp_script(server_config)

    def _direct_vasp_script(self, server_config: dict) -> str:
        """``<mpiexec> vasp_<variant>`` invocation.

        The launcher comes from ``server_config["mpiexec"]``,
        defaulting to ``mpiexec`` (LUMI sets ``srun``).  The full
        command is exported as ``VASP_COMMAND`` and then invoked,
        mirroring the legacy gorun script.
        """
        vasp_binary = os.path.join(
            os.environ["VASP_PATH"], "bin", f"vasp_{self.vasp_variant}"
        )
        mpiexec = server_config.get("mpiexec", "mpiexec")
        return (
            f'export VASP_COMMAND="{mpiexec} {vasp_binary}"\n'
            "$VASP_COMMAND"
        )

    def _incar_py_script(self, path: Path) -> str:
        """ASE-wrapped script when INCAR.py is present."""
        print(
            colored(
                "Found INCAR.py.  Using instead of directly running VASP.",
                "yellow",
            )
        )
        return (
            'export VASP_COMMAND="gorun vasp --local --no-incar-py --force '
            '--no-clean --keep POSCAR"\n'
            "python <<EOF\n"
            f"{_PYTHON_HEADER}\n"
            f"$(cat INCAR.py)\n"
            f"{_PYTHON_FINALIZER}\n"
            "EOF"
        )

    # ------------------------------------------------------------------
    # Backup excludes
    # ------------------------------------------------------------------

    def backup_excludes(self) -> list[str]:
        return ["WAVECAR"]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _has_incar_chain(path: Path) -> bool:
    """Return True when ``INCAR.{0,1,2,...}`` files exist."""
    return bool(sorted(path.glob("INCAR.[0-9]*")))


def _rotate_incar_chain(path: Path) -> None:
    """If converged with remaining INCAR chains, rotate the first one in."""
    if not directory_converged_p(str(path)):
        return
    chains = sorted(path.glob("INCAR.[0-9]*"))
    if not chains:
        return
    print(
        colored(
            f"Converged, but found additional INCARs: {chains}.  "
            f"Replacing INCAR with {chains[0]}",
            "yellow",
        )
    )
    incar = path / "INCAR"
    incar.rename(path / "INCAR.old")
    chains[0].rename(incar)


def _modify_incar(path: Path, mods: dict[str, str]) -> None:
    """Apply key=value modifications to INCAR."""
    from pymatgen.io.vasp.inputs import Incar

    incar_path = path / "INCAR"
    incar = Incar.from_file(str(incar_path))
    incar_before = incar.copy()

    for key, val in mods.items():
        if val == "None":
            incar.pop(key, None)
        else:
            incar[key] = val

    incar.write_file(str(incar_path))
    incar_diff = incar_before.diff(incar).get("Different")
    if incar_diff is not None and len(incar_diff) > 0:
        print(colored(f"Changed INCAR: {incar_diff}", "yellow"))
    else:
        print(colored("Leaving INCAR unchanged", "yellow"))


def _clear_useless_files(path: Path) -> None:
    """Clear empty CHG, CHGCAR, REPORT, WAVECAR if we are about to re-run."""
    if directory_contains_vasp_outputp(str(path)) or (
        (path / "INCAR.py").is_file()
    ):
        clear_useless_vasp_files(str(path))


def _regenerate_potcar(dir_path: str) -> None:
    """Call ``generate_potcar`` with ``keep_existing=False``."""
    generate_potcar(dir_path, keep_existing=False)
